apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  templete:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: b00mgr3rt/my-app:latest
          ports:
            - containerPort: 3000
